<?php

use Carbon\Carbon;
use Illuminate\Database\Seeder;

use App\Models\Car;
use App\Models\Series;
use App\Models\Type;

class CarsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $mainline = Type::where('name', 'Mainline')->first()->id;

        $cars = [
            [
                'number' => 1,
                'name' => '2 Jet Z',
                'colour' => 'Silver',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'HW Dream Garage')->first()->id,
                'series_number' => 1,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 1,
                'name' => '2 Jet Z',
                'colour' => 'Blue',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'HW Dream Garage')->first()->id,
                'series_number' => 1,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 0,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 2,
                'name' => 'Nissan Skyline R32',
                'colour' => 'Dark Grey',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'HW Turbo')->first()->id,
                'series_number' => 5,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 2,
                'name' => 'Nissan Skyline R32',
                'colour' => 'Dark Grey',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'HW Turbo')->first()->id,
                'series_number' => 5,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 1,
                'owned' => 0,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 3,
                'name' => 'Land Rover Series III Pickup',
                'colour' => 'Light Blue',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'Baja Blazers')->first()->id,
                'series_number' => 10,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 3,
                'name' => 'Land Rover Series III Pickup',
                'colour' => 'Beige',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'Baja Blazers')->first()->id,
                'series_number' => 10,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 0,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 4,
                'name' => 'Tooligan',
                'colour' => 'Green',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'Experimotors')->first()->id,
                'series_number' => 4,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 4,
                'name' => 'Tooligan',
                'colour' => 'Purple',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'Experimotors')->first()->id,
                'series_number' => 4,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 0,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 5,
                'name' => 'Gotta Go',
                'colour' => 'Purple',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'Experimotors')->first()->id,
                'series_number' => 6,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 6,
                'name' => 'Bubble Matic',
                'colour' => 'Red',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'Experimotors')->first()->id,
                'series_number' =>  10,
                'treasure_hunt' => 1,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 7,
                'name' => 'Road Bandit',
                'colour' => 'Yellow',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'HW Metro')->first()->id,
                'series_number' => 2,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 7,
                'name' => 'Road Bandit',
                'colour' => 'Red',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'HW Metro')->first()->id,
                'series_number' => 2,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 8,
                'name' => 'Diaper Dragger',
                'colour' => 'Blue',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'HW Metro')->first()->id,
                'series_number' => 6,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 8,
                'name' => 'Diaper Dragger',
                'colour' => 'Pink',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'HW Metro')->first()->id,
                'series_number' => 6,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 9,
                'name' => 'Batmobile',
                'colour' => 'Silver Chrome',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'Batman')->first()->id,
                'series_number' => 3,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 9,
                'name' => 'Batmobile',
                'colour' => 'Gold Chrome',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'Batman')->first()->id,
                'series_number' => 3,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 10,
                'name' => 'Honda Monkey Z50',
                'colour' => 'Red',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'Honda')->first()->id,
                'series_number' => 3,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 10,
                'name' => 'Honda Monkey Z50',
                'colour' => 'White',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'Honda')->first()->id,
                'series_number' => 3,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 11,
                'name' => '85 Honda City Turbo II',
                'colour' => 'Silver',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'Honda')->first()->id,
                'series_number' => 5,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 11,
                'name' => '85 Honda City Turbo II',
                'colour' => 'Red',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'Honda')->first()->id,
                'series_number' => 5,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 12,
                'name' => 'Night Shifter',
                'colour' => 'Flat Black',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'HW Race Day')->first()->id,
                'series_number' => 10,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 13,
                'name' => 'Octane',
                'colour' => 'Red',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'HW Screen Time')->first()->id,
                'series_number' => 8,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 13,
                'name' => 'Octane',
                'colour' => 'Green',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'HW Screen Time')->first()->id,
                'series_number' => 8,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 14,
                'name' => 'Snoopy',
                'colour' => 'Red',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'HW Screen Time')->first()->id,
                'series_number' => 9,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 15,
                'name' => '69 Chevelle',
                'colour' => 'Green',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'Tooned')->first()->id,
                'series_number' => 4,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 15,
                'name' => '69 Chevelle',
                'colour' => 'Silver Chrome',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'Tooned')->first()->id,
                'series_number' => 4,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 16,
                'name' => 'HW Formula Solar',
                'colour' => 'Blue',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'X-Raycers')->first()->id,
                'series_number' => 6,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 16,
                'name' => 'HW Formula Solar',
                'colour' => 'Red',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'X-Raycers')->first()->id,
                'series_number' => 6,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 17,
                'name' => 'Carbonator',
                'colour' => 'Red',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'Fast Foodie')->first()->id,
                'series_number' => 2,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 17,
                'name' => 'Carbonator',
                'colour' => 'Blue',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'Fast Foodie')->first()->id,
                'series_number' => 2,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 18,
                'name' => 'Chill Mill',
                'colour' => 'White',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'Fast Foodie')->first()->id,
                'series_number' => 3,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 18,
                'name' => 'Chill Mill',
                'colour' => 'Green',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'Fast Foodie')->first()->id,
                'series_number' => 3,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 19,
                'name' => '2005 Mustang',
                'colour' => 'Yellow',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'HW Dream Garage')->first()->id,
                'series_number' => 2,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 19,
                'name' => '2005 Mustang',
                'colour' => 'Green',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'HW Dream Garage')->first()->id,
                'series_number' => 2,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 20,
                'name' => '18 COPO Camara SS',
                'colour' => 'Silver',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'HW Dream Garage')->first()->id,
                'series_number' => 3,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 20,
                'name' => '18 COPO Camara SS',
                'colour' => 'Grey',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'HW Dream Garage')->first()->id,
                'series_number' => 3,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 21,
                'name' => 'Aero Pod',
                'colour' => 'Purple',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'HW Dream Garage')->first()->id,
                'series_number' => 2,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 21,
                'name' => 'Aero Pod',
                'colour' => 'Orange',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'X-Raycers')->first()->id,
                'series_number' => 2,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 22,
                'name' => 'Wheelie Chair',
                'colour' => 'Pink',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'HW Ride-Ons')->first()->id,
                'series_number' => 4,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 22,
                'name' => 'Wheelie Chair',
                'colour' => 'Purple',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'HW Ride-Ons')->first()->id,
                'series_number' => 4,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 0,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 23,
                'name' => '98 Subaru Impreza 22B STI',
                'colour' => 'Blue',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'HW Ride-Ons')->first()->id,
                'series_number' => 1,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 23,
                'name' => '98 Subaru Impreza 22B STI',
                'colour' => 'Red',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'HW Ride-Ons')->first()->id,
                'series_number' => 1,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 0,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 24,
                'name' => 'Pixel Shaker',
                'colour' => 'Red',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'HW Screen Time')->first()->id,
                'series_number' => 1,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 24,
                'name' => 'Pixel Shaker',
                'colour' => 'Blue',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'HW Screen Time')->first()->id,
                'series_number' => 1,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 0,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 25,
                'name' => 'Indy 500 Oval',
                'colour' => 'Teal',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'Speed Blur')->first()->id,
                'series_number' => 3,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 25,
                'name' => 'Indy 500 Oval',
                'colour' => 'Pink',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'Speed Blur')->first()->id,
                'series_number' => 3,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 26,
                'name' => 'HW Warp Speeder',
                'colour' => 'Blue',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'Track Stars')->first()->id,
                'series_number' => 3,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 26,
                'name' => 'HW Warp Speeder',
                'colour' => 'Silver',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'Track Stars')->first()->id,
                'series_number' => 3,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 0,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 27,
                'name' => 'Dune It Up',
                'colour' => 'Purple',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'Baja Blazers')->first()->id,
                'series_number' => 7,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 27,
                'name' => 'Dune It Up',
                'colour' => 'Silver',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'Baja Blazers')->first()->id,
                'series_number' => 7,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 0,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 28,
                'name' => 'HW450F',
                'colour' => 'Yellow',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'Baja Blazers')->first()->id,
                'series_number' => 8,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 28,
                'name' => 'HW450F',
                'colour' => 'Black',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'Baja Blazers')->first()->id,
                'series_number' => 8,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 29,
                'name' => 'Hyper Rocker',
                'colour' => 'Red',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'Baja Blazers')->first()->id,
                'series_number' => 9,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 29,
                'name' => 'Hyper Rocker',
                'colour' => 'Silver Chrome',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'Baja Blazers')->first()->id,
                'series_number' => 9,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 30,
                'name' => 'Heavy Hitcher',
                'colour' => 'Purple',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'Experimotors')->first()->id,
                'series_number' => 7,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 30,
                'name' => 'Heavy Hitcher',
                'colour' => 'Silver Chrome',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'Experimotors')->first()->id,
                'series_number' => 7,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 31,
                'name' => 'HW Armored Truck',
                'colour' => 'Silver Chrome',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'HW Metro')->first()->id,
                'series_number' => 4,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 31,
                'name' => 'HW Armored Truck',
                'colour' => 'Red',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'HW Metro')->first()->id,
                'series_number' => 4,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 32,
                'name' => 'The Haulinator',
                'colour' => 'Green',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'HW Metro')->first()->id,
                'series_number' => 8,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 33,
                'name' => 'Mercedes-Benz Unimog 1300',
                'colour' => 'Black',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'HW Metro')->first()->id,
                'series_number' => 10,
                'treasure_hunt' => 1,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 34,
                'name' => '76 Greenwood Corvette',
                'colour' => 'Gold',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'HW Race Day')->first()->id,
                'series_number' => 4,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 34,
                'name' => '76 Greenwood Corvette',
                'colour' => 'Light Blue',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'HW Race Day')->first()->id,
                'series_number' => 4,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 35,
                'name' => 'Ford GT40',
                'colour' => 'Light Blue',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'HW Race Day')->first()->id,
                'series_number' => 8,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 35,
                'name' => 'Ford GT40',
                'colour' => 'Metallic Blue',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'HW Race Day')->first()->id,
                'series_number' => 8,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 1,
                'owned' => 0,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 36,
                'name' => 'Sword Warthog',
                'colour' => 'Red',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'HW Screen Time')->first()->id,
                'series_number' => 7,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 37,
                'name' => 'RV There Yet',
                'colour' => 'Red',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'Tooned')->first()->id,
                'series_number' => 1,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 37,
                'name' => 'RV There Yet',
                'colour' => 'Blue',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'Tooned')->first()->id,
                'series_number' => 1,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 0,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 38,
                'name' => 'Cool-One',
                'colour' => 'White',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'Tooned')->first()->id,
                'series_number' => 5,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 38,
                'name' => 'Cool-One',
                'colour' => 'Black',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'Tooned')->first()->id,
                'series_number' => 5,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 39,
                'name' => 'Roller Toaster',
                'colour' => 'Light Blue',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'Fast Foodie')->first()->id,
                'series_number' => 4,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 40,
                'name' => '71 El Camino',
                'colour' => 'Grey',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'HW Dream Garage')->first()->id,
                'series_number' => 8,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 41,
                'name' => 'Hi-Tech Missile',
                'colour' => 'Red',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'X-Raycers')->first()->id,
                'series_number' => 5,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 41,
                'name' => 'Hi-Tech Missile',
                'colour' => 'Orange',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'X-Raycers')->first()->id,
                'series_number' => 5,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 0,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 42,
                'name' => 'Pedal de Metal',
                'colour' => 'Purple',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'X-Raycers')->first()->id,
                'series_number' => 7,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 43,
                'name' => '95 Mazda RX7',
                'colour' => 'Orange',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'HW Turbo')->first()->id,
                'series_number' => 4,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 43,
                'name' => '95 Mazda RX7',
                'colour' => 'Blue',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'HW Turbo')->first()->id,
                'series_number' => 4,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 44,
                'name' => 'Porsche Panamera Turbo S E-Hybrid Sport Turismo',
                'colour' => 'White',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'Porsche')->first()->id,
                'series_number' => 3,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 44,
                'name' => 'Porsche Panamera Turbo S E-Hybrid Sport Turismo',
                'colour' => 'Dark Blue',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'Porsche')->first()->id,
                'series_number' => 3,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 45,
                'name' => 'Porsche 917 LH',
                'colour' => 'Purple',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'Porsche')->first()->id,
                'series_number' => 4,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 46,
                'name' => 'Slide Kick',
                'colour' => 'Red',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'Experimotors')->first()->id,
                'series_number' => 8,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 47,
                'name' => '89 Porsche 944 Turbo',
                'colour' => 'Red',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'Porsche')->first()->id,
                'series_number' => 1,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 47,
                'name' => '89 Porsche 944 Turbo',
                'colour' => 'Gold',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'Porsche')->first()->id,
                'series_number' => 1,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 48,
                'name' => 'Power Rocket',
                'colour' => 'Red',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'X-Raycers')->first()->id,
                'series_number' => 9,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 48,
                'name' => 'Power Rocket',
                'colour' => 'Blue',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'X-Raycers')->first()->id,
                'series_number' => 9,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 0,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 49,
                'name' => 'Gruppo x24',
                'colour' => 'Orange',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'HW Track Stars')->first()->id,
                'series_number' => 3,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 49,
                'name' => 'Gruppo x24',
                'colour' => 'Yellow',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'HW Track Stars')->first()->id,
                'series_number' => 3,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 0,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'number' => 50,
                'name' => 'Dodge Viper SRT10ACR ',
                'colour' => 'Dark Metallic Red',
                'year' => 2020,
                'type_id' => $mainline,
                'series_id' => Series::where('name', 'HW Race Day')->first()->id,
                'series_number' => 7,
                'treasure_hunt' => 0,
                'super_treasure_hunt' => 0,
                'owned' => 1,
                'notes' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
        ];
    }
}
